/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.App;

/**
 *
 * @author Max
 */
public class Simulador extends javax.swing.JFrame {

    BackEnd.App aplicacion;

    /**
     * Creates new form Simulador
     */
    // Main de la aplicación
    public Simulador() {
        initComponents();
        aplicacion = new App();
        aplicacion.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        productorControles = new javax.swing.JLabel();
        productorPaquetes = new javax.swing.JLabel();
        ensamblador = new javax.swing.JLabel();
        productorConsolas = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        edoCronometrador = new javax.swing.JLabel();
        cronometrador = new javax.swing.JLabel();
        unidadesDisponibles = new javax.swing.JLabel();
        almacenControles = new javax.swing.JLabel();
        almacenConsolas = new javax.swing.JLabel();
        almacenPaquetes = new javax.swing.JLabel();
        edoGerente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setPreferredSize(new java.awt.Dimension(806, 530));

        jPanel1.setBackground(new java.awt.Color(66, 66, 66));

        jButton6.setBackground(new java.awt.Color(216, 67, 21));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("DESPEDIR");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton6.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton6.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(216, 67, 21));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("DESPEDIR");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(46, 125, 50));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CONTRATAR");
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(46, 125, 50));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("CONTRATAR");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton7.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        productorControles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productorControles.setForeground(new java.awt.Color(255, 255, 255));
        productorControles.setText("Productor de Controles");

        productorPaquetes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productorPaquetes.setForeground(new java.awt.Color(255, 255, 255));
        productorPaquetes.setText("Productor de Paquetes");

        ensamblador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ensamblador.setForeground(new java.awt.Color(255, 255, 255));
        ensamblador.setText("Ensamblador");

        productorConsolas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productorConsolas.setForeground(new java.awt.Color(255, 255, 255));
        productorConsolas.setText("Productor de Consolas");

        jButton4.setBackground(new java.awt.Color(216, 67, 21));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DESPEDIR");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(46, 125, 50));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CONTRATAR");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(216, 67, 21));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DESPEDIR");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(46, 125, 50));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CONTRATAR");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        edoCronometrador.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        edoCronometrador.setForeground(new java.awt.Color(255, 255, 255));
        edoCronometrador.setText("Estado Cronometrador");

        cronometrador.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cronometrador.setForeground(new java.awt.Color(255, 255, 255));
        cronometrador.setText("Cronometrador");

        unidadesDisponibles.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        unidadesDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        unidadesDisponibles.setText("Unidades Disponibles");

        almacenControles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        almacenControles.setForeground(new java.awt.Color(255, 255, 255));
        almacenControles.setText("Controles");

        almacenConsolas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        almacenConsolas.setForeground(new java.awt.Color(255, 255, 255));
        almacenConsolas.setText("Consolas");

        almacenPaquetes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        almacenPaquetes.setForeground(new java.awt.Color(255, 255, 255));
        almacenPaquetes.setText("Paquetes");

        edoGerente.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        edoGerente.setForeground(new java.awt.Color(255, 255, 255));
        edoGerente.setText("Estado Gerente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productorConsolas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productorControles))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, 0)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ensamblador)
                                    .addComponent(productorPaquetes))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(almacenPaquetes)
                            .addComponent(almacenControles)
                            .addComponent(almacenConsolas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(unidadesDisponibles)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cronometrador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edoCronometrador)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edoGerente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productorConsolas)
                    .addComponent(almacenConsolas))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productorControles)
                    .addComponent(almacenControles))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productorPaquetes)
                    .addComponent(almacenPaquetes))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ensamblador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(unidadesDisponibles)
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cronometrador)
                    .addComponent(edoCronometrador)
                    .addComponent(edoGerente))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //BOTON PARA AGREGAR UN PRODUCTOR DE CONTROLES
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        aplicacion.agregarProductorControles();        
    }//GEN-LAST:event_jButton2ActionPerformed
    //BOTON PARA AGREGAR UN PRODUCTOR DE CONSOLAS
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        aplicacion.agregarProductorConsolas();        
    }//GEN-LAST:event_jButton3ActionPerformed
    //BOTON PARA AGREGAR UN PRODUCTOR DE PAQUETES
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        aplicacion.agregarProductorPaquetes();        
    }//GEN-LAST:event_jButton5ActionPerformed
    //BOTON PARA DESPEDIR UN PRODUCTOR DE CONTROLES
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aplicacion.despedirProductorControles();         
    }//GEN-LAST:event_jButton1ActionPerformed
    //BOTON PARA DESPEDIR UN PRODUCTOR DE CONSOLAS
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        aplicacion.despedirProductorConsolas();        
    }//GEN-LAST:event_jButton4ActionPerformed
    //BOTON PARA DESPEDIR UN PRODUCTOR DE PAQUETES
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        aplicacion.despedirProductorPaquetes(); 
    }//GEN-LAST:event_jButton6ActionPerformed
    //BOTON PARA AGREGAR UN ENSAMBLADOR
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        aplicacion.agregarEnsamblador();
    }//GEN-LAST:event_jButton7ActionPerformed
    //BOTON PARA DESPEDIR UN ENSAMBLADOR
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        aplicacion.despedirEnsamblador();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Simulador Sim = new Simulador();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Sim.setVisible(true);
            }
        });
        while (true) {
            Sim.asignar();
        }
    }
    
    // asignar() es el metodo encargado de actualizar las etiquetas del frontend con la información de la fabrica en tiempo real.
    public void asignar() {
        productorConsolas.setText("PRODUCTORES DE CONSOLAS:  "+Integer.toString(aplicacion.getProductoresConsolas()));
        productorControles.setText("PRODUCTORES DE CONTROLES: "+Integer.toString(aplicacion.getProductoresControles()));
        productorPaquetes.setText("PRODUCTORES DE PAQUETES:  "+Integer.toString(aplicacion.getProductoresPaquetes()));
        almacenConsolas.setText("ESPACIO OCUPADO CONSOLAS: "+Integer.toString(aplicacion.getAlmacenConsolas().getEspacioOcupado())+" DISPONIBLE: "+Integer.toString(aplicacion.getAlmacenConsolas().getTamanoMaximo() - aplicacion.getAlmacenConsolas().getEspacioOcupado()));
        almacenControles.setText("ESPACIO OCUPADO CONTROLES: "+Integer.toString(aplicacion.getAlmacenControles().getEspacioOcupado())+" DISPONIBLE:"+Integer.toString(aplicacion.getAlmacenControles().getTamanoMaximo() - aplicacion.getAlmacenControles().getEspacioOcupado()));
        almacenPaquetes.setText("ESPACIO OCUPADO PAQUETES: "+Integer.toString(aplicacion.getAlmacenPaquetes().getEspacioOcupado())+" DISPONIBLE: "+Integer.toString(aplicacion.getAlmacenPaquetes().getTamanoMaximo() - aplicacion.getAlmacenPaquetes().getEspacioOcupado()));
        //almacenConsolasDisp.setText("ESPACIO DISPONIBLE: "+Integer.toString(aplicacion.getAlmacenConsolas().getTamanoMaximo() - aplicacion.getAlmacenConsolas().getEspacioOcupado()));
        //almacenControlesDisp.setText("hehexd2 "+Integer.toString(aplicacion.getAlmacenControles().getTamanoMaximo() - aplicacion.getAlmacenControles().getEspacioOcupado()));
        //almacenPaquetesDisp.setText("hehexd3 "+Integer.toString(aplicacion.getAlmacenPaquetes().getTamanoMaximo() - aplicacion.getAlmacenPaquetes().getEspacioOcupado()));
        ensamblador.setText("ENSAMBLADORES: "+Integer.toString(aplicacion.getEnsambladores()));
        unidadesDisponibles.setText("UNIDADES DISPONIBLES: "+Integer.toString(aplicacion.getAlmacenEnsamblados()[0]));
        edoGerente.setText("ESTADO DEL GERENTE: "+Boolean.toString(aplicacion.getGerente().isDormido()));
        edoCronometrador.setText("ESTADO DEL CRONOMETRADOR: "+Boolean.toString(aplicacion.getCronometrador().isDormido()));
        cronometrador.setText("DIAS FALTANTES: "+Integer.toString(aplicacion.getCronometrador().getDiasFaltantes()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel almacenConsolas;
    private javax.swing.JLabel almacenControles;
    private javax.swing.JLabel almacenPaquetes;
    private javax.swing.JLabel cronometrador;
    private javax.swing.JLabel edoCronometrador;
    private javax.swing.JLabel edoGerente;
    private javax.swing.JLabel ensamblador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productorConsolas;
    private javax.swing.JLabel productorControles;
    private javax.swing.JLabel productorPaquetes;
    private javax.swing.JLabel unidadesDisponibles;
    // End of variables declaration//GEN-END:variables
}
